project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "MTA ridership Analysis"
  author:
    - Balaganesh Manikandan (bm3237)
    - Rohit Sadavarte (rss2251)
  repo-url: https://github.com/sadavarterohit/mta-ridership
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - test.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


